---
name: "Latest pylint-nautobot"

on:  # yamllint disable-line rule:truthy rule:comments
  schedule:
    - cron: "0 3 */2 * *"  # every other day at 3am
  # TBD: Remove running on push
  push: ~


jobs:
  latest-pylint-nautobot:
    runs-on: "ubuntu-22.04"
    env:
      INVOKE_NAUTOBOT_DEV_EXAMPLE_LOCAL: "True"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v6"
      - name: "Linting: black"
        # TBD: Fix ref to `develop` branch
        run: "poetry run invoke pylint ref=u/snaselj-fix-deps"

